import { v4 as uuid } from "uuid";
import { longkurti,handbag,shoes,premiumjacket,kidsdress, denimjacket,kidsjeans, womenkurti, printedkurti, bluekurti,levisbag, levisbag2,
  wallet,girlsfrock,longfrock,shirt,tshirt, leatherjacket } from "../../assets/images/index";


  export const products = [
  {
    _id: uuid(),
    title: "women plazzo set",
    price: "1200",
    image: longkurti,
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "2",
    categoryName: "womens-clothing",
  },
  {
    _id: uuid(),
    title: "Fancy Hand Bag",
    image: handbag,
    price: "1500",
    badge: "Out of stock",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "3",
    categoryName: "women-accessories",
  },
  {
    _id: uuid(),
    title: "Puma Shoes",
    image: shoes,
    price: "1100",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "4",
    categoryName: "mens-clothing",
  },
  {
    _id: uuid(),
    title: "Graceful men jacket",
    image: premiumjacket,
    price: "2000",
    badge: "Out of stock",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "3",
    categoryName: "mens-clothing",
  },
  {
    _id: uuid(),
    title: "Classy Boys Clothing Set",
    image: kidsdress,
    price: "1000",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "4",
    categoryName: "kids-clothing",
  },
  {
    _id: uuid(),
    title: "Stylish Denim Jacket",
    image: denimjacket,
    price: "1900",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "4",
    categoryName: "mens-clothing",
  },
  {
    _id: uuid(),
    title: "Classy Jeans",
    image: kidsjeans,
    price: "1000",
    badge: "Out of stock",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "2",
    categoryName: "kids-clothing",
  },
  {
    _id: uuid(),
    title: "Elegant stylish kurti",
    image: womenkurti,
    price: "1500",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "3",
    categoryName: "womens-clothing",
  },
  {
    _id: uuid(),
    title: "Printed straight kurti",
    image: printedkurti,
    price: "1100",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "2",
    categoryName: "womens-clothing",
  },
  {
    _id: uuid(),
    title: "Kashvi Graceful Kurtis",
    image: bluekurti,
    price: "1200",
    badge: "Out of stock",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "3",
    categoryName: "womens-clothing",
  },
  {
    _id: uuid(),
    title: "Voguish Fancy Hand Bag",
    image: levisbag,
    price: "1100",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "5",
    categoryName: "women-accessories",
  },
  {
    _id: uuid(),
    title: "Graceful Stylish Hand Bag",
    image: levisbag2,
    price: "1500",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "4",
    categoryName: "women-accessories",
  },
  {
    _id: uuid(),
    title: "Trendy women wallet",
    image: wallet,
    price: "1000",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "4",
    categoryName: "women-accessories",
  },
  {
    _id: uuid(),
    title: "Tinkle Funky Girls Frock",
    image: girlsfrock,
    price: "1000",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "3",
    categoryName: "kids-clothing",
  },
  {
    _id: uuid(),
    title: "Partywear Women Frock",
    image: longfrock,
    price: "1600",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "2",
    categoryName: "womens-clothing",
  },
  {
    _id: uuid(),
    title: "CLassic Men Shirt",
    image: shirt,
    price: "1300",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "3",
    categoryName: "mens-clothing",
  },
  {
    _id: uuid(),
    title: "Manlino Men Tshirt",
    image: tshirt,
    price: "1700",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "4",
    categoryName: "mens-clothing",
  },
  {
    _id: uuid(),
    title: "Denim Jeans",
    image: leatherjacket,
    price: "2000",
    badge: "None",
    discount: "(20% OFF)",
    wishlist: "false",
    rating: "3",
    categoryName: "mens-clothing",
  },
];
